apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-data
  namespace: veltro
  labels:
    app: veltro
    component: redis
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: standard
  resources:
    requests:
      storage: 1Gi
