use serde::Deserialize;
use std::collections::HashMap;
use std::sync::Arc;
use tokio::sync::RwLock;

use crate::vault::{VaultConfig, VaultError};

/// Vault Client for secret operations.
///
/// This client provides a high-level interface to HashiCorp Vault for:
/// - Reading static secrets from KV v2 store
/// - Generating dynamic database credentials with automatic lease management
/// - Managing lease lifecycle (renewal and revocation)
/// - Handling authentication and namespace configuration
///
/// # Example
///
/// ```rust,no_run
/// use veltro_backend::vault::{VaultClient, VaultConfig};
///
/// #[tokio::main]
/// async fn main() -> Result<(), Box<dyn std::error::Error>> {
///     let config = VaultConfig::new(
///         "https://vault.example.com".to_string(),
///         "your-vault-token".to_string(),
///         "stellar-app".to_string(),
///     );
///     let client = VaultClient::new(config).await?;
///
///     // Read a static secret
///     let api_key = client.read_secret("api/keys/stellar", None).await?;
///
///     // Generate database credentials
///     let db_creds = client.get_database_credentials("read-write").await?;
///
///     Ok(())
/// }
/// ```
pub struct VaultClient {
    http_client: reqwest::Client,
    config: VaultConfig,
    lease_manager: Arc<RwLock<HashMap<String, LeaseInfo>>>,
}

/// Information about an active Vault lease
#[allow(dead_code)]
#[derive(Clone, Debug)]
struct LeaseInfo {
    lease_id: String,
    lease_duration: u64,
    renewable: bool,
    created_at: std::time::Instant,
}

/// Response from Vault KV v2 read operation
#[allow(dead_code)]
#[derive(Debug, Deserialize)]
struct KvReadResponse {
    request_id: String,
    lease_id: String,
    lease_duration: u64,
    renewable: bool,
    data: KvData,
}

#[allow(dead_code)]
#[derive(Debug, Deserialize)]
struct KvData {
    data: HashMap<String, serde_json::Value>,
    metadata: serde_json::Value,
}

/// Database credentials generated by Vault
///
/// Contains temporary credentials for database access with configurable TTL.
/// These credentials are automatically renewed by the lease manager
/// to ensure continuous database connectivity.
///
/// # Fields
///
/// * `username` - Database username (typically includes random identifier)
/// * `password` - Database password (temporary, expires with lease)
/// * `ttl` - Time-to-live in seconds before credentials expire
///
/// # Example
///
/// ```rust,no_run
/// use veltro_backend::vault::client::DatabaseCredentials;
///
/// // Credentials received from Vault
/// let creds: DatabaseCredentials = DatabaseCredentials {
///     username: "v-stellar-app-abc123".to_string(),
///     password: "temp-password-xyz789".to_string(),
///     ttl: 3600, // 1 hour
/// };
/// ```
#[derive(Debug, Deserialize, Clone)]
pub struct DatabaseCredentials {
    pub username: String,
    pub password: String,
    pub ttl: u64,
}

/// Response from Vault secret read
#[allow(dead_code)]
#[derive(Debug, Deserialize)]
struct VaultSecretResponse {
    request_id: String,
    lease_id: String,
    lease_duration: u64,
    renewable: bool,
    data: serde_json::Value,
}

impl VaultClient {
    /// Create a new Vault client
    ///
    /// Initializes HTTP client with 30-second timeout and validates Vault connection.
    /// The client will automatically handle namespace prefixes and authentication.
    ///
    /// # Arguments
    ///
    /// * `config` - Vault configuration containing address, token, and namespace
    ///
    /// # Returns
    ///
    /// * `Result<VaultClient, VaultError>` - Client instance or error if connection fails
    ///
    /// # Example
    ///
    /// ```rust,no_run
    /// use veltro_backend::vault::{VaultClient, VaultConfig};
    ///
    /// #[tokio::main]
    /// async fn main() -> Result<(), Box<dyn std::error::Error>> {
    ///     let config = VaultConfig::new(
    ///         "https://vault.example.com".to_string(),
    ///         "your-token".to_string(),
    ///         "stellar-app".to_string(),
    ///     );
    ///     let client = VaultClient::new(config).await?;
    ///     println!("Vault client initialized successfully");
    ///     Ok(())
    /// }
    /// ```
    pub async fn new(config: VaultConfig) -> Result<Self, VaultError> {
        let http_client = reqwest::Client::builder()
            .timeout(std::time::Duration::from_secs(30))
            .build()
            .map_err(|e| VaultError::ClientError(e.to_string()))?;

        let client = Self {
            http_client,
            config,
            lease_manager: Arc::new(RwLock::new(HashMap::new())),
        };

        client.health_check().await?;
        Ok(client)
    }

    /// Check Vault health
    async fn health_check(&self) -> Result<(), VaultError> {
        let url = format!("{}/v1/sys/health", self.config.vault_addr);
        match self.http_client.get(&url).send().await {
            Ok(resp) => {
                if resp.status().is_success() || resp.status().as_u16() == 473 {
                    Ok(())
                } else {
                    Err(VaultError::VaultUnavailable)
                }
            }
            Err(_) => Err(VaultError::VaultUnavailable),
        }
    }

    /// Read a static secret from KV v2
    ///
    /// Retrieves a secret from Vault's KV v2 store. The secret can be a specific
    /// field within a secret path or the entire secret data.
    ///
    /// # Arguments
    ///
    /// * `path` - Secret path in Vault (e.g., "api/keys/stellar")
    /// * `field` - Optional specific field within the secret (None returns all data)
    ///
    /// # Returns
    ///
    /// * `Result<String, VaultError>` - Secret value as string or error
    ///
    /// # Example
    ///
    /// ```rust,no_run
    /// use veltro_backend::vault::{VaultClient, VaultConfig};
    ///
    /// #[tokio::main]
    /// async fn main() -> Result<(), Box<dyn std::error::Error>> {
    ///     let config = VaultConfig::new(
    ///         "https://vault.example.com".to_string(),
    ///         "your-vault-token".to_string(),
    ///         "stellar-app".to_string(),
    ///     );
    ///     let client = VaultClient::new(config).await?;
    ///
    ///     // Read specific field
    ///     let api_key = client.read_secret("api/keys/stellar", Some("private_key")).await?;
    ///
    ///     // Read entire secret
    ///     let app_config = client.read_secret("app/config", None).await?;
    ///
    ///     Ok(())
    /// }
    /// ```
    pub async fn read_secret(&self, path: &str, field: Option<&str>) -> Result<String, VaultError> {
        let url = format!(
            "{}/v1/data/{}",
            self.config.vault_addr,
            path.trim_start_matches('/')
        );

        let resp = self
            .http_client
            .get(&url)
            .header("X-Vault-Token", &self.config.vault_token)
            .send()
            .await
            .map_err(|e| VaultError::RequestError(e.to_string()))?;

        if !resp.status().is_success() {
            return Err(VaultError::SecretNotFound(path.to_string()));
        }

        let secret: KvReadResponse = resp
            .json()
            .await
            .map_err(|e| VaultError::ParseError(e.to_string()))?;

        if let Some(field_name) = field {
            secret
                .data
                .data
                .get(field_name)
                .and_then(|v| v.as_str())
                .map(std::string::ToString::to_string)
                .ok_or_else(|| VaultError::FieldNotFound(field_name.to_string()))
        } else {
            secret
                .data
                .data
                .values()
                .next()
                .and_then(|v| v.as_str())
                .map(std::string::ToString::to_string)
                .ok_or(VaultError::NoDataInSecret)
        }
    }

    /// Request dynamic `PostgreSQL` database credentials
    ///
    /// Generates temporary database credentials from Vault's database secrets engine.
    /// These credentials are automatically managed by the lease system to ensure
    /// they don't expire during application runtime.
    ///
    /// **Currently unused**: the backend is SQLite-only
    /// (`docs/adr/0001-sqlite-vs-postgres.md`), so there is no Postgres
    /// instance for Vault's database secrets engine to issue credentials
    /// against, and no call site in this codebase invokes this method.
    /// Kept for if that decision is revisited.
    ///
    /// # Arguments
    ///
    /// * `role` - Database role for credential generation (e.g., "read-write", "read-only")
    ///
    /// # Returns
    ///
    /// * `Result<DatabaseCredentials, VaultError>` - Database credentials with lease info
    ///
    /// # Example
    ///
    /// ```rust,no_run
    /// use veltro_backend::vault::{VaultClient, VaultConfig};
    ///
    /// #[tokio::main]
    /// async fn main() -> Result<(), Box<dyn std::error::Error>> {
    ///     let config = VaultConfig::new(
    ///         "https://vault.example.com".to_string(),
    ///         "your-vault-token".to_string(),
    ///         "stellar-app".to_string(),
    ///     );
    ///     let client = VaultClient::new(config).await?;
    ///
    ///     // Generate read-write credentials
    ///     let creds = client.get_database_credentials("read-write").await?;
    ///     println!("Username: {}, TTL: {}s", creds.username, creds.ttl);
    ///
    ///     Ok(())
    /// }
    /// ```
    pub async fn get_database_credentials(
        &self,
        role: &str,
    ) -> Result<DatabaseCredentials, VaultError> {
        let url = format!("{}/v1/database/creds/{}", self.config.vault_addr, role);

        let resp = self
            .http_client
            .get(&url)
            .header("X-Vault-Token", &self.config.vault_token)
            .send()
            .await
            .map_err(|e| VaultError::RequestError(e.to_string()))?;

        if !resp.status().is_success() {
            return Err(VaultError::CredentialsFailed(role.to_string()));
        }

        let secret: VaultSecretResponse = resp
            .json()
            .await
            .map_err(|e| VaultError::ParseError(e.to_string()))?;

        let data = &secret.data;
        let username = data["username"]
            .as_str()
            .ok_or(VaultError::ParseError("Missing username".to_string()))?
            .to_string();
        let password = data["password"]
            .as_str()
            .ok_or(VaultError::ParseError("Missing password".to_string()))?
            .to_string();

        let mut leases = self.lease_manager.write().await;
        leases.insert(
            secret.lease_id.clone(),
            LeaseInfo {
                lease_id: secret.lease_id,
                lease_duration: secret.lease_duration,
                renewable: secret.renewable,
                created_at: std::time::Instant::now(),
            },
        );

        Ok(DatabaseCredentials {
            username,
            password,
            ttl: secret.lease_duration,
        })
    }

    /// Renew a lease before it expires
    pub async fn renew_lease(&self, lease_id: &str) -> Result<(), VaultError> {
        let url = format!("{}/v1/sys/leases/renew", self.config.vault_addr);

        let body = serde_json::json!({ "lease_id": lease_id });

        let resp = self
            .http_client
            .put(&url)
            .header("X-Vault-Token", &self.config.vault_token)
            .json(&body)
            .send()
            .await
            .map_err(|e| VaultError::RequestError(e.to_string()))?;

        if resp.status().is_success() {
            Ok(())
        } else {
            Err(VaultError::LeaseRenewalFailed(lease_id.to_string()))
        }
    }

    /// Renew the service's own Vault token before its TTL expires.
    pub async fn renew_self(&self) -> Result<(), VaultError> {
        let url = format!("{}/v1/auth/token/renew-self", self.config.vault_addr);
        let resp = self
            .http_client
            .post(&url)
            .header("X-Vault-Token", &self.config.vault_token)
            .send()
            .await
            .map_err(|e| VaultError::RequestError(e.to_string()))?;
        if resp.status().is_success() {
            Ok(())
        } else {
            Err(VaultError::LeaseRenewalFailed("self".to_string()))
        }
    }

    /// Revoke a lease
    pub async fn revoke_lease(&self, lease_id: &str) -> Result<(), VaultError> {
        let url = format!("{}/v1/sys/leases/revoke", self.config.vault_addr);

        let body = serde_json::json!({ "lease_id": lease_id });

        let resp = self
            .http_client
            .put(&url)
            .header("X-Vault-Token", &self.config.vault_token)
            .json(&body)
            .send()
            .await
            .map_err(|e| VaultError::RequestError(e.to_string()))?;

        if resp.status().is_success() {
            let mut leases = self.lease_manager.write().await;
            leases.remove(lease_id);
            Ok(())
        } else {
            Err(VaultError::LeaseRevokeFailed(lease_id.to_string()))
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn lease_info_fields() {
        let lease = LeaseInfo {
            lease_id: "lease/db/abc123".to_string(),
            lease_duration: 3600,
            renewable: true,
            created_at: std::time::Instant::now(),
        };
        assert_eq!(lease.lease_id, "lease/db/abc123");
        assert_eq!(lease.lease_duration, 3600);
        assert!(lease.renewable);
    }

    #[test]
    fn database_credentials_fields() {
        let creds = DatabaseCredentials {
            username: "v-user-abc".to_string(),
            password: "s3cr3t".to_string(),
            ttl: 3600,
        };
        assert_eq!(creds.username, "v-user-abc");
        assert_eq!(creds.ttl, 3600);
    }

    #[tokio::test]
    async fn new_returns_vault_unavailable_when_no_server() {
        let config = VaultConfig::new(
            "http://127.0.0.1:19999".to_string(), // nothing listening here
            "s.fake".to_string(),
            "stellar-app".to_string(),
        );
        let result = VaultClient::new(config).await;
        assert!(matches!(result, Err(VaultError::VaultUnavailable)));
    }
}
