#!/usr/bin/env bash
# Deploy the integrated Soroban contract to testnet.
# Outputs contract IDs to contracts/.env.testnet
#
# Usage: ./scripts/deploy-contracts-testnet.sh [--source <identity>] [--fee <stroop>]
#
# Prerequisites:
#   - stellar CLI installed and authenticated (stellar keys list)
#   - STELLAR_ACCOUNT env var set, or pass --source <identity>
#   - Network: testnet (https://soroban-testnet.stellar.org)
#
# Only veltro is deployed — it is the sole contract wired to the
# backend via SNAPSHOT_CONTRACT_ID. Other contract crates are archived; see
# contracts/archive/README.md.

set -euo pipefail

# ── Configuration ─────────────────────────────────────────────────────────────

CONTRACTS_DIR="$(cd "$(dirname "$0")/../contracts" && pwd)"
ENV_FILE="${CONTRACTS_DIR}/.env.testnet"
NETWORK="testnet"
RPC_URL="https://soroban-testnet.stellar.org"
NETWORK_PASSPHRASE="Test SDF Network ; September 2015"
FEE="${STELLAR_FEE:-100}"

# ── Parse arguments ────────────────────────────────────────────────────────────

SOURCE="${STELLAR_ACCOUNT:-}"

while [[ $# -gt 0 ]]; do
    case $1 in
        --source) SOURCE="$2"; shift 2 ;;
        --fee)    FEE="$2";    shift 2 ;;
        *) echo "Unknown argument: $1"; exit 1 ;;
    esac
done

if [[ -z "${SOURCE}" ]]; then
    echo "Error: deployer identity not set."
    echo "  Set STELLAR_ACCOUNT env var or pass --source <identity>"
    exit 1
fi

# ── Helpers ────────────────────────────────────────────────────────────────────

log()  { echo "[$(date -u +%H:%M:%S)] $*"; }
info() { echo "  $*"; }

deploy_contract() {
    local name="$1"   # human-readable label
    local wasm="$2"   # path to .wasm file
    local alias="$3"  # env-file key (e.g. ACCESS_CONTROL_CONTRACT_ID)

    log "Deploying ${name}..."
    if [[ ! -f "${wasm}" ]]; then
        echo "  Error: wasm not found at ${wasm}"
        echo "  Run 'cd contracts && cargo build --release --target wasm32v1-none' first."
        exit 1
    fi

    # `|| true` on the pipeline: with `set -e`, a transient deploy failure
    # (grep finding no 56-char ID) would otherwise kill the script right here,
    # silently skipping the error message below — this way the `-z` check
    # gets a chance to report which contract failed before exiting.
    local contract_id
    contract_id=$(stellar contract deploy \
        --wasm "${wasm}" \
        --source "${SOURCE}" \
        --network "${NETWORK}" \
        --fee "${FEE}" \
        2>&1 | grep -E '^[A-Z0-9]{56}$' | tail -1) || true

    if [[ -z "${contract_id}" ]]; then
        echo "  Error: failed to deploy ${name} — no contract ID returned."
        echo "  This can be a transient RPC/network hiccup — try re-running."
        exit 1
    fi

    info "${alias}=${contract_id}"
    echo "${alias}=${contract_id}" >> "${ENV_FILE}"
    echo "${contract_id}"
}

# ── Build ──────────────────────────────────────────────────────────────────────

log "Building all contracts for release..."
(cd "${CONTRACTS_DIR}" && cargo build --release --target wasm32v1-none 2>&1 | tail -5)
log "Build complete."

# ── Deploy ─────────────────────────────────────────────────────────────────────

WASM_DIR="${CONTRACTS_DIR}/target/wasm32v1-none/release"

# Start fresh env file
cat > "${ENV_FILE}" <<EOF
# Testnet contract IDs — generated by deploy-contracts-testnet.sh
# Network:    ${NETWORK}
# RPC URL:    ${RPC_URL}
# Passphrase: ${NETWORK_PASSPHRASE}
# Deployer:   ${SOURCE}

EOF

log "Starting deployment to ${NETWORK}..."
echo ""

VELTRO_ID=$(deploy_contract \
    "veltro" \
    "${WASM_DIR}/veltro.wasm" \
    "VELTRO_CONTRACT_ID")

# ── Summary ────────────────────────────────────────────────────────────────────

echo ""
log "Contract deployed successfully."
log "Contract IDs written to: ${ENV_FILE}"
echo ""
echo "  VELTRO_CONTRACT_ID=${VELTRO_ID}"
echo ""
log "Source the env file with: source ${ENV_FILE}"
log "Set SNAPSHOT_CONTRACT_ID=\$VELTRO_CONTRACT_ID in backend/.env"
